version: '3.3'
services:
      redis:
        ports:
          - '6666:6379'
        image: redis:4.0.5-alpine
        container_name: redis
        command: ["redis-server", "--appendonly", "yes", "--requirepass notsecurepassword"]
        hostname: redis
        volumes:
          - redis-data:/data

volumes:
    redis-data:
